# Generated by Django 5.0.14 on 2026-09-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "ordering": ["name"],
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
    ]
