# Generated by Django 5.0.14 on 2026-09-03 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="AutoZap", max_length=200)),
                ("currency", models.CharField(default="KZT", max_length=8)),
                ("default_min_stock", models.PositiveIntegerField(default=5)),
                (
                    "seller_discount_limit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        help_text="Максимальный % скидки, который продавец может дать без подтверждения владельца",
                        max_digits=5,
                    ),
                ),
                ("return_days_limit", models.PositiveIntegerField(default=14)),
                ("shifts_enabled", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Настройки",
                "verbose_name_plural": "Настройки",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(blank=True, max_length=64)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал аудита",
                "verbose_name_plural": "Журнал аудита",
                "ordering": ["-created_at"],
            },
        ),
    ]
