# Generated by Django 5.0.14 on 2026-09-03 18:19

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Бренд",
                "verbose_name_plural": "Бренды",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(db_index=True, max_length=64)),
                (
                    "oem_code",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True, db_index=True, max_length=64, null=True
                    ),
                ),
                (
                    "search_key",
                    models.CharField(blank=True, db_index=True, max_length=400),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "шт"),
                            ("set", "компл"),
                            ("l", "л"),
                            ("kg", "кг"),
                        ],
                        default="pcs",
                        max_length=10,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avg_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("min_stock", models.PositiveIntegerField(default=5)),
                (
                    "applicability",
                    models.TextField(
                        blank=True,
                        help_text="Применимость к авто, напр. Toyota Camry 40/50",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                ("photo", models.TextField(blank=True, max_length=100, null=True)),
                ("note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.category",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Товар",
                "verbose_name_plural": "historical Товары",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(max_length=64, unique=True)),
                (
                    "oem_code",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "search_key",
                    models.CharField(blank=True, db_index=True, max_length=400),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("pcs", "шт"),
                            ("set", "компл"),
                            ("l", "л"),
                            ("kg", "кг"),
                        ],
                        default="pcs",
                        max_length=10,
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "avg_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("min_stock", models.PositiveIntegerField(default=5)),
                (
                    "applicability",
                    models.TextField(
                        blank=True,
                        help_text="Применимость к авто, напр. Toyota Camry 40/50",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("note", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("analogs", models.ManyToManyField(blank=True, to="catalog.product")),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["sku"], name="catalog_pro_sku_2c4c34_idx"),
                    models.Index(
                        fields=["oem_code"], name="catalog_pro_oem_cod_b10c02_idx"
                    ),
                    models.Index(
                        fields=["barcode"], name="catalog_pro_barcode_58f8f8_idx"
                    ),
                ],
            },
        ),
    ]
