# Generated by Django 5.0.14 on 2026-09-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproduct",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
    ]
